on:
  workflow_call:
    secrets:
      docker_username:
        required: false  # Optional, only required if Docker login is needed
      docker_password:
        required: false  # Optional, only required if Docker login is needed
    inputs:
      authors:
        type: string
        required: true
      vendor:
        type: string
        required: true
      docker_url:
        type: string
        required: false
      image_name:
        type: string
        required: true   # Image name is required for Docker build and push
      image_tag:
        type: string
        required: false  # Optional, default to release-please version if not provided
  
  
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      major: ${{ steps.release-please.outputs.major }}
      minor: ${{ steps.release-please.outputs.minor }}
      patch: ${{ steps.release-please.outputs.patch }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          release-type: go

  release:
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release_created
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker_url }}
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          annotations: |
            org.opencontainers.image.authors=${{ inputs.authors }}
            org.opencontainers.image.vendor=${{ inputs.vendor }}
          images: |
            ${{ inputs.docker_url }}/${{ inputs.image_name }}:v${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
            ${{ inputs.docker_url }}/${{ inputs.image_name }}:latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ inputs.docker_url }}/${{ inputs.image_name }}:v${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
            ${{ inputs.docker_url }}/${{ inputs.image_name }}:latest
